# Generated by Django 4.1.3 on 2022-11-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.cargo"
            ),
        ),
    ]
