# Generated by Django 4.1.3 on 2022-11-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_cargo_alter_users_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="cargo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.cargo"
            ),
        ),
    ]
