# Generated by Django 4.1.3 on 2022-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cpf',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='users',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
