# Generated by Django 4.1.3 on 2022-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paciente", "0002_paciente_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
