# Generated by Django 4.1.3 on 2022-12-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='convenio',
        ),
    ]
