# Generated by Django 4.1.3 on 2022-12-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="especialidades",
            field=models.CharField(
                choices=[
                    ("1", "Cardiologista"),
                    ("2", "Neurologista"),
                    ("3", "Pediatra"),
                    ("4", "Oftamologista"),
                    ("5", "Ginecologista"),
                    ("6", "Clinico Geral"),
                ],
                max_length=1,
            ),
        ),
    ]
