# Generated by Django 4.1.3 on 2022-12-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0002_alter_medico_especialidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="medico",
            name="especialidades",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="medico.especialidades"
            ),
        ),
    ]
