# Generated by Django 4.1.3 on 2022-12-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_paciente_convenio'),
        ('medico', '0001_initial'),
        ('consulta', '0002_alter_marcarconsulta_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcarconsulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
        migrations.AlterField(
            model_name='marcarconsulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
