# Generated by Django 4.1.3 on 2022-12-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_marcarconsulta_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcarconsulta',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
