# Generated by Django 4.1.3 on 2022-12-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_marcarconsulta_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcarconsulta',
            name='data',
        ),
    ]
